### ISSUE TITLE
occasional slice panics in extractTrigrams

### ISSUE THREAD

**Issue by grobian** [grobian/carbonserver#17]
2015/05/26 15:30:42 http: panic serving 10.196.70.109:42704: runtime error: slic
e bounds out of range
goroutine 1402 [running]:
net/http.func·011()
        /usr/lib64/go/src/net/http/server.go:1130 +0xbb
main.extractTrigrams(0xc20a04eb90, 0x49, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/carbonserver-20150423_143116-1_788b2eacdeaf.el6/go
path/src/grobian/carbonserver/main.go:777 +0x16b
main.expandGlobs(0xc20a04eb90, 0x49, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/carbonserver-20150423_143116-1_788b2eacdeaf.el6/go
path/src/grobian/carbonserver/main.go:194 +0x910
main.findHandler(0x7f23bd53fb78, 0xc20f1b4780, 0xc20c6e9380)
        /builddir/build/BUILD/carbonserver-20150423_143116-1_788b2eacdeaf.el6/gopath/src/grobian/carbonserver/main.go:274 +0x2f1
github.com/dgryski/httputil.func·002(0x7f23bd53fb78, 0xc20f1b4780, 0xc20c6e9380)
        /builddir/build/BUILD/carbonserver-20150423_143116-1_788b2eacdeaf.el6/gopath/src/github.com/dgryski/httputil/times.go:26 +0x76
github.com/dgryski/httputil.func·003(0x7f23bd53fb78, 0xc20f1b4780, 0xc20c6e9380)
        /builddir/build/BUILD/carbonserver-20150423_143116-1_788b2eacdeaf.el6/gopath/src/github.com/dgryski/httputil/track.go:40 +0xc7
net/http.HandlerFunc.ServeHTTP(0xc20802aef0, 0x7f23bd53fb78, 0xc20f1b4780, 0xc20c6e9380)
        /usr/lib64/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20800a780, 0x7f23bd53fb78, 0xc20f1b4780, 0xc20c6e9380)
        /usr/lib64/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20811c120, 0x7f23bd53fb78, 0xc20f1b4780, 0xc20c6e9380)
        /usr/lib64/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20bbc6dc0)
        /usr/lib64/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib64/go/src/net/http/server.go:1751 +0x35e

**Comment by dgryski** [comment]
A bit of fuzzing shows this happens on invalid globs, for example `[00`.

I'll fix this and the one in carbonmem too.  Should probably extract `extractTrigrams()` somewhere at some point too, since we have two copies.
