### ISSUE TITLE
{documentation} list of args the app takes

### ISSUE THREAD

**Issue by gmlwall** [grobian/carbonserver#20]
Hey, and thank you for all your help!

Im running carbonserver in conjunction with carbonzipper and it would be a great help to me if you colud provide a list of args that the app takes so i can configure it a bit more :)

Sorry im not a dev and i cant interpret the code, if you could provide a list, i can write up some chkconfig-able init scripts for our servers with a few options per env.

Many thanks

**Comment by grobian** [comment]
I think running carbonserver -h would say most of it

-p port
-maxexpand maximum glob expansions to perform (this controls memory usage mostly for monster queries)
-maxprocs how many cpus you want carbonserver to use
-logdir what dir to log to
-scanfreq frequency in seconds when to update the in-memory cache of available whisper files on disk (this is used when "finding" metrics, not for fetch queries)

**Comment by gmlwall** [comment]
great many thanks :) -
as a side note, carbon-server / zipper are great, the stack is performing really well and can handle tons or metrics. Really impressed by it.
The core of its the original graphite/carbon, but it has carbon-c-relay/zipper/server tying it all together to allow it to scale out to multiple servers. So anyway, i though a cool name for this suite of apps would be 

"Covalent"

After covalent bonds which are what allow carbon to bind together to allow create things like graphite and diamond :)

**Comment by grobian** [comment]
That's a nice find :)  I'm thinking of writing that long awaited blog post describing in detail what we do, how and why.  I guess we could use "Covalent" to give it a nice title!
