### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jjneely** [grobian/carbonserver#25]
I'd really like to use parts/all of carbonserver in some of my Graphite related work.  However, my client require that code I use/incorporate be licensed and I do not see a license file here.  

Would it be possible to add a LICENSE file?

**Comment by dgryski** [comment]
The license will likely be MIT or Apache.  Fabian will commit it tomorrow.  (hopefully...)

**Comment by jjneely** [comment]
Thanks!

**Comment by grobian** [comment]
will add apache 2 licence

**Comment by grobian** [comment]
fixed in 0677dc9
